import { Router, type IRouter } from "express";
import healthRouter from "./health";
import restaurantImportRouter from "./restaurant-import";
import nearbyRouter from "./nearby";
import outreachRouter from "./outreach";
import repliesRouter from "./replies";
import gmailRouter from "./gmail";
import subscriptionsRouter from "./subscriptions";
import portalRouter from "./portal";
import premiumRouter from "./premium";
import searchRouter from "./search";
import homepageRouter from "./homepage";
import cityRouter from "./city";
import regionsRouter from "./regions";
import countriesRouter from "./countries";
import cuisineRouter from "./cuisine";
import directoryRouter from "./directory";
import restaurantRouter from "./restaurant";
import claimRouter from "./claim";
import analyticsRouter from "./analytics";
import recommendationsRouter from "./recommendations";
import reviewsRouter from "./reviews";
import autocompleteRouter from "./autocomplete";
import menusRouter from "./menus";
import bookingsRouter from "./bookings";
import matchRouter from "./match";
import favouritesRouter from "./favourites";
import classifyRouter from "./classify";
import chatRouter from "./chat";
import trendingRouter from "./trending";
import rewardsRouter from "./rewards";
import rankRouter from "./rank";
import qrRouter from "./qr";
import brandRouter from "./brand";
import aiPhotoRouter from "./ai-photo";
import menuScanRouter from "./menu-scan";
import heatmapRouter from "./heatmap";
import forecastRouter from "./forecast";
import photoRouter from "./photo";
import googleReviewsRouter from "./google-reviews";

const router: IRouter = Router();

router.use(healthRouter);
router.use(restaurantImportRouter);
router.use(nearbyRouter);
router.use(outreachRouter);
router.use(repliesRouter);
router.use(gmailRouter);
router.use(subscriptionsRouter);
router.use(portalRouter);
router.use(premiumRouter);
router.use(searchRouter);
router.use(homepageRouter);
router.use(cityRouter);
router.use(regionsRouter);
router.use(countriesRouter);
router.use(cuisineRouter);
router.use(directoryRouter);
router.use(restaurantRouter);
router.use(claimRouter);
router.use(analyticsRouter);
router.use(recommendationsRouter);
router.use(reviewsRouter);
router.use(autocompleteRouter);
router.use(menusRouter);
router.use(bookingsRouter);
router.use(matchRouter);
router.use(favouritesRouter);
router.use(classifyRouter);
router.use(chatRouter);
router.use(trendingRouter);
router.use(rewardsRouter);
router.use(rankRouter);
router.use(qrRouter);
router.use(brandRouter);
router.use(aiPhotoRouter);
router.use(menuScanRouter);
router.use(heatmapRouter);
router.use(forecastRouter);
router.use(photoRouter);
router.use(googleReviewsRouter);

export default router;
