// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/food-advisor/BrandStyle.tsx": () => import("../components/mockups/food-advisor/BrandStyle.tsx"),
  "./components/mockups/food-advisor/Dashboard.tsx": () => import("../components/mockups/food-advisor/Dashboard.tsx"),
  "./components/mockups/food-advisor/Details.tsx": () => import("../components/mockups/food-advisor/Details.tsx"),
  "./components/mockups/food-advisor/Discover.tsx": () => import("../components/mockups/food-advisor/Discover.tsx"),
  "./components/mockups/food-advisor/Goals.tsx": () => import("../components/mockups/food-advisor/Goals.tsx"),
  "./components/mockups/food-advisor/Map.tsx": () => import("../components/mockups/food-advisor/Map.tsx"),
  "./components/mockups/food-advisor/Notifications.tsx": () => import("../components/mockups/food-advisor/Notifications.tsx"),
  "./components/mockups/food-advisor/OwnerEntry.tsx": () => import("../components/mockups/food-advisor/OwnerEntry.tsx"),
  "./components/mockups/food-advisor/Photos.tsx": () => import("../components/mockups/food-advisor/Photos.tsx"),
  "./components/mockups/food-advisor/Profile.tsx": () => import("../components/mockups/food-advisor/Profile.tsx"),
  "./components/mockups/food-advisor/Restaurant.tsx": () => import("../components/mockups/food-advisor/Restaurant.tsx"),
  "./components/mockups/food-advisor/Search.tsx": () => import("../components/mockups/food-advisor/Search.tsx"),
  "./components/mockups/food-advisor/Settings.tsx": () => import("../components/mockups/food-advisor/Settings.tsx"),
  "./components/mockups/food-advisor/Splash.tsx": () => import("../components/mockups/food-advisor/Splash.tsx"),
  "./components/mockups/food-advisor/Subscription.tsx": () => import("../components/mockups/food-advisor/Subscription.tsx"),
  "./components/mockups/food-advisor/Welcome.tsx": () => import("../components/mockups/food-advisor/Welcome.tsx")
};
